const mongoose = require('mongoose');

const Schema =mongoose.Schema;

const Students = new Schema({
//an id automatically generated by mongodb
    //  id:{
// type:String,
// required:true
//  },
name : {
  type:String,
  required:true
 },
 Age:{
  type:Number,
  required:true
 },
 Mark1:{
  type:Number,
  required:true
 },
 Mark2:{
  type:Number,
  required:true
 },
 Mark3:{
  type:Number,
  required:true
 }
});

module.exports = mongoose.model('Students',Students);